version: '3'
services:
  organice:
    image: 'twohundredok/organice:latest'
    ports:
      - '5000:5000'
    logging:
      driver: json-file
    environment:
      ORGANICE_WEBDAV_URL: http://webdav.example.com
  apache-webdav:
    build:
      context: ./
      dockerfile: ./doc/webdav/Dockerfile
    ports:
      - '8080:80'
    logging:
      driver: json-file
